### ISSUE TITLE
Short getting started or Install guide

### ISSUE THREAD

**Issue by im2ex** [mlajtos/moniel#6]
Hello, 
please add some short getting started or install guide.

I tried for more than two hours without being able to run the demo.
(I am coming from the embedded world and are not familiar with js tool-chain)

If I just open moniel.html locally, I see a grey window without any function.
I tried with firefox on linux and with firefox, chrome, explorer on windows.

Am I supposed to start startDevEnv.sh? Then babel and http-server are needed. Which?
Things I tried (on ubuntu first 14.4 then 16.4):
```
sudo apt-get install babel-1.4.0
sudo apt-get install openbabel
npm install babel
and some more
```
startDevEnv.sh was not happy with any of those.
Same question would arise for http-server.

Hope to be able to play with this very interesting project, and also use it as an example to learn js visualization. Thanks a lot for publishing.

**Comment by mlajtos** [comment]
Hello :)

I fixed some stuff and tried it also on Ubuntu, so it should work now.

I added [instructions](https://github.com/mlajtos/moniel#setup), but you will need NPM, which you can install by ```sudo apt-get install npm```.

Enjoy.

**Comment by im2ex** [comment]
Thanks for the fast reaction.

>>and tried it also on Ubuntu,

Hmm, anything else I need to install? What OS / npm Version are you using?
I seem to face some version problems. I'll look more into this tomorrow.

With ubuntu 16.4, and npm from there, after a lot of successful module loading (almost 400 in node_modules), I end up with
```
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.17
npm WARN moniel@0.0.1 No license field.
npm ERR! Linux 4.4.0-62-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! electron@1.4.15 postinstall: `node install.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the electron@1.4.15 postinstall script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the electron package,
npm ERR! not with npm itself.
```

(PS: just for completeness: ```cd moniel``` before ```npm install```)

**Comment by mlajtos** [comment]
Electron is trying to run "node" command, but on your system it is "nodejs".

One possible solution is to upgrade NPM to higher version that can deal with that (3.7.0 and higher) or you can make a symlink to the actual binary: ```sudo ln -s /usr/bin/nodejs /usr/bin/node```.

(Thank you. :) )

**Comment by im2ex** [comment]
Thanks a lot! Link did the trick.
Working fine now.

**Comment by datlife** [comment]
@mlajtos Perfect! Confirm that it works!

However, I still receive two warnings. Not sure if it would affect the program 
```
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.1.2
```

**Comment by mlajtos** [comment]
@dat-ai Awesome ;)

Those two warnings shouldn't be any problem. :)
